/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    products: Product;
    categories: Category;
    dealers: Dealer;
    teams: Team;
    orders: Order;
    pages: Page;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    categories: {
      produkte: 'products';
    };
  };
  collectionsSelect: {
    products: ProductsSelect<false> | ProductsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    dealers: DealersSelect<false> | DealersSelect<true>;
    teams: TeamsSelect<false> | TeamsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    home: Home;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Alle Batterien. Jedes Produkt erzeugt automatisch eine Detailseite.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  /**
   * Wird automatisch aus dem Titel erzeugt, kann aber überschrieben werden.
   */
  slug: string;
  status: 'published' | 'draft';
  /**
   * Bestimmt, auf welcher Kategorieseite die Batterie erscheint und unter welchem Menüpunkt sie zu finden ist. Jede Batterie gehört zu genau einer Kategorie.
   */
  category: number | Category;
  sortOrder?: number | null;
  featured?: boolean | null;
  /**
   * z. B. „12V Lithium Starterbatterie“
   */
  subtitle?: string | null;
  /**
   * Kleines Label auf der Produktkachel, z. B. „Bestseller“. Leer lassen für keins.
   */
  badge?: string | null;
  /**
   * Erscheint auf Kacheln und in der Suchvorschau.
   */
  shortDescription?: string | null;
  keyData?: {
    voltage?: string | null;
    capacity?: string | null;
    current?: string | null;
    weight?: string | null;
  };
  highlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  price: number;
  /**
   * Optional.
   */
  compareAtPrice?: number | null;
  sku?: string | null;
  availability?: ('in_stock' | 'low_stock' | 'on_request' | 'sold_out') | null;
  deliveryTime?: string | null;
  /**
   * Dreizehnstellig, aus der Preisliste. Wird für Preisportale und Warenwirtschaft gebraucht.
   */
  ean?: string | null;
  /**
   * Bruttogewicht inklusive Verpackung — Grundlage für die Versandkosten.
   */
  shippingWeight?: number | null;
  /**
   * Erscheint klein unter dem Preis.
   */
  shippingNote?: string | null;
  mainImage?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Wird auf der Produktdetailseite eingebunden. Leer lassen, wenn kein Video gewünscht ist.
   */
  video?: {
    /**
     * Beliebiges Format: https://youtu.be/ID, https://www.youtube.com/watch?v=ID oder nur die ID.
     */
    url?: string | null;
    title?: string | null;
    description?: string | null;
    /**
     * Wird vor dem Klick angezeigt. Ohne Bild erscheint eine neutrale Fläche mit Play-Button.
     */
    previewImage?: (number | null) | Media;
  };
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  specs?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  downloads?:
    | {
        label: string;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. Bleibt ein Feld leer, wird automatisch der Seiteninhalt verwendet.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Die Kategorie-Übersichtsseiten (Motorsport-, Rennsport- und Motorradbatterien).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * Wird automatisch aus dem Titel erzeugt, kann aber überschrieben werden.
   */
  slug: string;
  sortOrder?: number | null;
  /**
   * Ergibt sich aus dem Feld „Kategorie“ am jeweiligen Produkt. Die Reihenfolge auf der Kategorieseite steuert das Feld „Reihenfolge“ am Produkt.
   */
  produkte?: {
    docs?: (number | Product)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  eyebrow?: string | null;
  headline: string;
  subline?: string | null;
  image?: (number | null) | Media;
  highlights?:
    | {
        title: string;
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. Bleibt ein Feld leer, wird automatisch der Seiteninhalt verwendet.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Kurze Bildbeschreibung — wichtig für SEO und Barrierefreiheit.
   */
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Händler und Einbaupartner. Die Koordinaten für die Umkreissuche werden beim Speichern automatisch aus der Postleitzahl ermittelt (Deutschland, Österreich, Schweiz).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dealers".
 */
export interface Dealer {
  id: number;
  name: string;
  /**
   * Wird automatisch aus dem Titel erzeugt, kann aber überschrieben werden.
   */
  slug: string;
  published?: boolean | null;
  /**
   * Erscheint mit Rahmen und weiter oben in der Liste.
   */
  featured?: boolean | null;
  /**
   * Mehrfachauswahl möglich.
   */
  status: ('haendler' | 'einbaupartner')[];
  /**
   * Eigene Bezeichnung, z. B. „Servicepartner“ oder „Schulungszentrum“. Erscheint als weiteres Etikett und ist mitfilterbar.
   */
  statusFreitext?: string | null;
  street?: string | null;
  postalCode?: string | null;
  city?: string | null;
  country?: ('DE' | 'AT' | 'CH') | null;
  /**
   * Werden beim Speichern aus der Postleitzahl ermittelt — für Deutschland, Österreich und die Schweiz. Für eine genauere Position hier von Hand eintragen und den Haken darunter setzen, dann bleiben die Werte unangetastet.
   */
  coordinates?: {
    lat?: number | null;
    lng?: number | null;
    /**
     * Verhindert, dass die automatische Ermittlung sie beim Speichern überschreibt.
     */
    manuell?: boolean | null;
  };
  contactPerson?: string | null;
  email?: string | null;
  phone?: string | null;
  /**
   * Mit oder ohne https:// — wird beim Speichern ergänzt.
   */
  website?: string | null;
  /**
   * Eine Zeile je Tag oder Zeitraum.
   */
  openingHours?: string | null;
  services?: ('beratung' | 'einbau' | 'werkstatt' | 'abholung' | 'vorort')[] | null;
  /**
   * Zwei bis drei Sätze, erscheinen auf der Karte des Händlers.
   */
  description?: string | null;
  logo?: (number | null) | Media;
  /**
   * Nur im Backend sichtbar, erscheint nicht auf der Website.
   */
  internalNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Ein Eintrag je Rennteam, entsprechend dem Fragebogen. Jeder Eintrag bekommt eine eigene Seite unter /teams. Felder, die leer bleiben, erscheinen auf der Seite nicht — es ist also kein Problem, einen Bogen nur teilweise ausgefüllt zu übernehmen.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams".
 */
export interface Team {
  id: number;
  teamName: string;
  /**
   * Wird automatisch aus dem Titel erzeugt, kann aber überschrieben werden.
   */
  slug: string;
  published?: boolean | null;
  /**
   * Erscheint in der Übersicht ganz oben und mit Rahmen.
   */
  featured?: boolean | null;
  /**
   * Kleinere Zahl steht weiter vorn. Bei gleicher Zahl zählt der Teamname.
   */
  sortOrder?: number | null;
  /**
   * Je Fahrer ein Eintrag. Erscheint auf der Teamseite und in der Übersicht.
   */
  drivers?:
    | {
        name: string;
        /**
         * Optional, z. B. „Stammfahrer“ oder „Teamchef“.
         */
        role?: string | null;
        photo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  location?: string | null;
  series?: string | null;
  /**
   * Wer seid ihr, wie seid ihr zum Rennsport gekommen und was zeichnet euch aus? Antwort des Teams, bitte nicht umschreiben.
   */
  intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  contactName?: string | null;
  contactEmail?: string | null;
  /**
   * Aus: Name und E-Mail stehen nur im Backend. An: beides erscheint auf der Teamseite. Bitte nur mit Einverständnis des Teams einschalten.
   */
  contactPublic?: boolean | null;
  /**
   * Mit oder ohne https:// — wird beim Speichern ergänzt.
   */
  website?: string | null;
  social?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Setzt das Team mehrere Fahrzeuge ein, bekommt jedes einen eigenen Eintrag.
   */
  vehicles?:
    | {
        manufacturer?: string | null;
        model?: string | null;
        year?: string | null;
        engine?: string | null;
        modifications?: string | null;
        /**
         * Verknüpft die Teamseite mit der Produktseite. Steht das Modell nicht zur Auswahl, das Feld darunter benutzen.
         */
        battery?: (number | null) | Product;
        /**
         * Nur nötig, wenn das eingesetzte Modell nicht im Shop steht — etwa eine Sonderanfertigung.
         */
        batteryOther?: string | null;
        /**
         * So, wie das Team es angegeben hat, z. B. „Saison 2024“ oder „März 2025“.
         */
        since?: string | null;
        reason?: string | null;
        experience?: string | null;
        photo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  results?:
    | {
        date?: string | null;
        event: string;
        placement?: string | null;
        id?: string | null;
      }[]
    | null;
  pastAchievements?:
    | {
        year?: string | null;
        title: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Vergangene Termine verschwinden auf der Website von selbst, sobald das Datum vorbei ist.
   */
  upcoming?:
    | {
        date: string;
        event: string;
        track?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  logo?: (number | null) | Media;
  /**
   * Erscheint in der Übersicht und oben auf der Teamseite. Ohne Bild bleibt dort der Markenhintergrund.
   */
  mainImage?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Nur im Backend sichtbar, erscheint nicht auf der Website.
   */
  internalNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Wird automatisch von Stripe befüllt. Zahlungsdaten liegen ausschließlich bei Stripe.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  orderNumber?: string | null;
  status?: ('paid' | 'processing' | 'shipped' | 'cancelled' | 'refunded') | null;
  email?: string | null;
  customerName?: string | null;
  phone?: string | null;
  shippingAddress?: {
    line1?: string | null;
    line2?: string | null;
    postalCode?: string | null;
    city?: string | null;
    country?: string | null;
  };
  items?:
    | {
        product?: (number | null) | Product;
        title?: string | null;
        sku?: string | null;
        quantity?: number | null;
        unitPrice?: number | null;
        lineTotal?: number | null;
        id?: string | null;
      }[]
    | null;
  subtotal?: number | null;
  shipping?: number | null;
  total?: number | null;
  stripe?: {
    sessionId?: string | null;
    paymentIntentId?: string | null;
    paymentStatus?: string | null;
  };
  customerNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Freie Textseiten wie Datenschutz, Impressum und AGB.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Wird automatisch aus dem Titel erzeugt, kann aber überschrieben werden.
   */
  slug: string;
  subtitle?: string | null;
  lastUpdated?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Optional. Bleibt ein Feld leer, wird automatisch der Seiteninhalt verwendet.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'dealers';
        value: number | Dealer;
      } | null)
    | ({
        relationTo: 'teams';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  category?: T;
  sortOrder?: T;
  featured?: T;
  subtitle?: T;
  badge?: T;
  shortDescription?: T;
  keyData?:
    | T
    | {
        voltage?: T;
        capacity?: T;
        current?: T;
        weight?: T;
      };
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  price?: T;
  compareAtPrice?: T;
  sku?: T;
  availability?: T;
  deliveryTime?: T;
  ean?: T;
  shippingWeight?: T;
  shippingNote?: T;
  mainImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  video?:
    | T
    | {
        url?: T;
        title?: T;
        description?: T;
        previewImage?: T;
      };
  description?: T;
  specs?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  downloads?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  sortOrder?: T;
  produkte?: T;
  eyebrow?: T;
  headline?: T;
  subline?: T;
  image?: T;
  highlights?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  body?: T;
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dealers_select".
 */
export interface DealersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  published?: T;
  featured?: T;
  status?: T;
  statusFreitext?: T;
  street?: T;
  postalCode?: T;
  city?: T;
  country?: T;
  coordinates?:
    | T
    | {
        lat?: T;
        lng?: T;
        manuell?: T;
      };
  contactPerson?: T;
  email?: T;
  phone?: T;
  website?: T;
  openingHours?: T;
  services?: T;
  description?: T;
  logo?: T;
  internalNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams_select".
 */
export interface TeamsSelect<T extends boolean = true> {
  teamName?: T;
  slug?: T;
  published?: T;
  featured?: T;
  sortOrder?: T;
  drivers?:
    | T
    | {
        name?: T;
        role?: T;
        photo?: T;
        id?: T;
      };
  location?: T;
  series?: T;
  intro?: T;
  contactName?: T;
  contactEmail?: T;
  contactPublic?: T;
  website?: T;
  social?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  vehicles?:
    | T
    | {
        manufacturer?: T;
        model?: T;
        year?: T;
        engine?: T;
        modifications?: T;
        battery?: T;
        batteryOther?: T;
        since?: T;
        reason?: T;
        experience?: T;
        photo?: T;
        id?: T;
      };
  results?:
    | T
    | {
        date?: T;
        event?: T;
        placement?: T;
        id?: T;
      };
  pastAchievements?:
    | T
    | {
        year?: T;
        title?: T;
        id?: T;
      };
  upcoming?:
    | T
    | {
        date?: T;
        event?: T;
        track?: T;
        url?: T;
        id?: T;
      };
  logo?: T;
  mainImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  internalNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  status?: T;
  email?: T;
  customerName?: T;
  phone?: T;
  shippingAddress?:
    | T
    | {
        line1?: T;
        line2?: T;
        postalCode?: T;
        city?: T;
        country?: T;
      };
  items?:
    | T
    | {
        product?: T;
        title?: T;
        sku?: T;
        quantity?: T;
        unitPrice?: T;
        lineTotal?: T;
        id?: T;
      };
  subtotal?: T;
  shipping?: T;
  total?: T;
  stripe?:
    | T
    | {
        sessionId?: T;
        paymentIntentId?: T;
        paymentStatus?: T;
      };
  customerNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  subtitle?: T;
  lastUpdated?: T;
  content?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Sämtliche Inhalte der Startseite — Hero, Teaser, Videos, Vorteile, Partner.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  eyebrow?: string | null;
  headline: string;
  /**
   * Dieser Textteil wird in Bulltron-Grün gesetzt. Muss exakt so in der Überschrift vorkommen.
   */
  headlineAccent?: string | null;
  subline?: string | null;
  primaryCtaLabel?: string | null;
  primaryCtaUrl?: string | null;
  secondaryCtaLabel?: string | null;
  secondaryCtaUrl?: string | null;
  /**
   * Füllt den gesamten Hero-Bereich. Ist ein Bild gesetzt, entfällt der Produktfreisteller rechts. Querformat, mindestens 2000 px breit.
   */
  backgroundImage?: (number | null) | Media;
  /**
   * Welcher Teil des Bildes sichtbar bleibt, wenn der Bereich schmaler wird.
   */
  backgroundFocus?: ('left' | 'center-left' | 'center' | 'center-right' | 'right') | null;
  /**
   * Wird nur angezeigt, solange kein Hintergrundbild gesetzt ist.
   */
  image?: (number | null) | Media;
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  teaser?: {
    enabled?: boolean | null;
    eyebrow?: string | null;
    headline?: string | null;
    text?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    image?: (number | null) | Media;
    imagePosition?: ('right' | 'left') | null;
    bullets?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    ctaLabel?: string | null;
    ctaUrl?: string | null;
  };
  categoriesHeadline?: string | null;
  categoriesSubline?: string | null;
  categoryCards?:
    | {
        category: number | Category;
        text?: string | null;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  productsHeadline?: string | null;
  productsSubline?: string | null;
  /**
   * Die Startseite zeigt höchstens drei Produkte. Leer lassen, dann werden automatisch die als „hervorgehoben“ markierten Produkte genommen — auch dort zählen nur die ersten drei.
   */
  featuredProducts?: (number | Product)[] | null;
  /**
   * Bis zu drei YouTube-Videos auf der Startseite.
   */
  videoSection?: {
    enabled?: boolean | null;
    eyebrow?: string | null;
    headline?: string | null;
    subline?: string | null;
    videos?:
      | {
          /**
           * https://youtu.be/ID, https://www.youtube.com/watch?v=ID oder nur die ID.
           */
          url: string;
          title?: string | null;
          description?: string | null;
          /**
           * Wird vor dem Klick angezeigt. Ohne Bild erscheint eine neutrale Fläche mit Play-Button.
           */
          previewImage?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  uspHeadline?: string | null;
  usps?:
    | {
        icon?: ('bolt' | 'shield' | 'weight' | 'temp' | 'truck' | 'support' | 'factory' | 'cycle') | null;
        title: string;
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  partnerHeadline?: string | null;
  partners?:
    | {
        name: string;
        logo?: (number | null) | Media;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  ctaBand?: {
    enabled?: boolean | null;
    headline?: string | null;
    text?: string | null;
    ctaLabel?: string | null;
    ctaUrl?: string | null;
  };
  /**
   * Optional. Bleibt ein Feld leer, wird automatisch der Seiteninhalt verwendet.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    noindex?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Logo, Navigation, Footer, Kontaktdaten, Versandkosten.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName?: string | null;
  tagline?: string | null;
  /**
   * Kompakte Fassung ohne Claim — im Header ist wenig Höhe.
   */
  logo?: (number | null) | Media;
  /**
   * Darf die vollständige Fassung mit Claim sein. Leer lassen, dann wird das Kopf-Logo verwendet.
   */
  footerLogo?: (number | null) | Media;
  defaultSeoDescription?: string | null;
  defaultSeoImage?: (number | null) | Media;
  mainNav?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  headerCtaLabel?: string | null;
  headerCtaUrl?: string | null;
  /**
   * Leer lassen zum Ausblenden.
   */
  announcement?: string | null;
  companyName?: string | null;
  street?: string | null;
  postalCode?: string | null;
  city?: string | null;
  phone?: string | null;
  mobile?: string | null;
  email?: string | null;
  /**
   * Erscheint im Footer. Leer lassen, wenn keine festen Zeiten genannt werden sollen.
   */
  openingHours?: string | null;
  footerText?: string | null;
  footerColumns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  copyright?: string | null;
  paymentNote?: string | null;
  /**
   * Dieser Betrag wird beim Kauf tatsächlich abgebucht. Lithium-Batterien sind Gefahrgut — bitte gegen die echten Konditionen des Versanddienstleisters prüfen.
   */
  shippingCost?: number | null;
  /**
   * 0 = nie versandfrei
   */
  freeShippingFrom?: number | null;
  taxRate?: number | null;
  /**
   * Erscheint auf der Stripe-Bezahlseite. Beide Felder leer lassen, wenn keine Lieferzeit zugesagt werden soll — dann steht dort nichts.
   */
  deliveryDaysMin?: number | null;
  deliveryDaysMax?: number | null;
  /**
   * ISO-Code, z. B. DE, AT, CH.
   */
  shippingCountries?:
    | {
        code: string;
        name: string;
        id?: string | null;
      }[]
    | null;
  checkoutNote?: string | null;
  legal?: {
    priceNote?: string | null;
    termsUrl?: string | null;
    privacyUrl?: string | null;
    imprintUrl?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  eyebrow?: T;
  headline?: T;
  headlineAccent?: T;
  subline?: T;
  primaryCtaLabel?: T;
  primaryCtaUrl?: T;
  secondaryCtaLabel?: T;
  secondaryCtaUrl?: T;
  backgroundImage?: T;
  backgroundFocus?: T;
  image?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  teaser?:
    | T
    | {
        enabled?: T;
        eyebrow?: T;
        headline?: T;
        text?: T;
        image?: T;
        imagePosition?: T;
        bullets?:
          | T
          | {
              text?: T;
              id?: T;
            };
        ctaLabel?: T;
        ctaUrl?: T;
      };
  categoriesHeadline?: T;
  categoriesSubline?: T;
  categoryCards?:
    | T
    | {
        category?: T;
        text?: T;
        image?: T;
        id?: T;
      };
  productsHeadline?: T;
  productsSubline?: T;
  featuredProducts?: T;
  videoSection?:
    | T
    | {
        enabled?: T;
        eyebrow?: T;
        headline?: T;
        subline?: T;
        videos?:
          | T
          | {
              url?: T;
              title?: T;
              description?: T;
              previewImage?: T;
              id?: T;
            };
      };
  uspHeadline?: T;
  usps?:
    | T
    | {
        icon?: T;
        title?: T;
        text?: T;
        id?: T;
      };
  partnerHeadline?: T;
  partners?:
    | T
    | {
        name?: T;
        logo?: T;
        url?: T;
        id?: T;
      };
  ctaBand?:
    | T
    | {
        enabled?: T;
        headline?: T;
        text?: T;
        ctaLabel?: T;
        ctaUrl?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  logo?: T;
  footerLogo?: T;
  defaultSeoDescription?: T;
  defaultSeoImage?: T;
  mainNav?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  headerCtaLabel?: T;
  headerCtaUrl?: T;
  announcement?: T;
  companyName?: T;
  street?: T;
  postalCode?: T;
  city?: T;
  phone?: T;
  mobile?: T;
  email?: T;
  openingHours?: T;
  footerText?: T;
  footerColumns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  copyright?: T;
  paymentNote?: T;
  shippingCost?: T;
  freeShippingFrom?: T;
  taxRate?: T;
  deliveryDaysMin?: T;
  deliveryDaysMax?: T;
  shippingCountries?:
    | T
    | {
        code?: T;
        name?: T;
        id?: T;
      };
  checkoutNote?: T;
  legal?:
    | T
    | {
        priceNote?: T;
        termsUrl?: T;
        privacyUrl?: T;
        imprintUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}